### ISSUE TITLE
External Monitor stays just lit black (HDMI) Notebook Intel integrated + Nvidia but should work on Intel

### ISSUE THREAD

**Issue by romanstingler** [hyprwm/aquamarine#40]
From the AQ PR my outstanding MultiMonitor Bug. 

I am using `Tag: v0.41.2-48-gf642fb97, commits: 4934` for now, as this is my office laptop, there everything is fine,
`DP-3` is my external HDMI monitor which stays black

I clean-built `hyprland-git  0.41.2.r166.0e86808e-1` the issue is still present. 
```
hyprcursor-git 0.1.9.r9.g4493a972-1
hypridle-git 0.1.2.r10.ge5366d34-1
hyprland-git  0.41.2.r166.0e86808e-1
hyprlang-git 0.5.2.r8.gadbefbf4-1
hyprlock-git 0.4.1.r3.gcf0e975f-1
hyprutils-git 0.2.1.r1.g0252fd13-1
hyprwayland-scanner-git 0.4.0.r4.ga048a6cb-1
```

```
~ ❯ printenv                                                                                       21:25
XDG_VTNR=1
SHLVL=2
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
SHELL=/usr/bin/fish
MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA=
EDITOR=vim
LOGNAME=roman
ELECTRON_USE_OZONE=1
GDK_BACKEND=wayland
XDG_SESSION_ID=1
MOZ_ENABLE_WAYLAND=1
PWD=/home/roman
OZONE_PLATFORM=wayland
DISPLAY=:0
HYPRCURSOR_SIZE=24
XDG_BACKEND=wayland
MOTD_SHOWN=pam
MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/system.slice/system-getty.slice/getty@tty1.service/memory.pressure
SUDO_RS_IS_UNSTABLE=I accept that my system may break unexpectedly
LANG=en_US.UTF-8
CREDENTIALS_DIRECTORY=/run/credentials/getty@tty1.service
XDG_CURRENT_DESKTOP=Hyprland
AQ_MGPU_NO_EXPLICIT=1
ELECTRON_OZONE_PLATFORM_HINT=auto
USER=roman
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
TERM=foot
HL_INITIAL_WORKSPACE_TOKEN=29848760-5e68-43c2-bed9-745f9796232b
XDG_SEAT=seat0
WAYLAND_DISPLAY=wayland-1
XCURSOR_SIZE=24
_JAVA_AWT_WM_NONREPARENTING=1
XDG_SESSION_TYPE=wayland
HOME=/home/roman
INVOCATION_ID=5f3182dd9bd94841b54e99d2448fcafb
COLORTERM=truecolor
XDG_SESSION_CLASS=user
MAIL=/var/spool/mail/roman
XDG_RUNTIME_DIR=/run/user/1000
HYPRLAND_CMD=hyprland
HYPRLAND_INSTANCE_SIGNATURE=f642fb97df5c69267a03452533de383ff8023570_1722885217_1265813201
NO_AT_BRIDGE=1
SYSTEMD_EXEC_PID=812
```
```
~ ❯ lspci -v | grep -E "VGA|3D"                                                                                                                                                                        1.439s 21:34
00:02.0 VGA compatible controller: Intel Corporation CometLake-H GT2 [UHD Graphics] (rev 05) (prog-if 00 [VGA controller])
01:00.0 3D controller: NVIDIA Corporation GP107GLM [Quadro P620] (rev a1)
```
```
~ ❯ inxi -G                                                                                                                                                                                                                                                                            21:44
Graphics:
  Device-1: Intel CometLake-H GT2 [UHD Graphics] driver: i915 v: kernel
  Device-2: NVIDIA GP107GLM [Quadro P620] driver: nvidia v: 555.58.02
  Device-3: Chicony Integrated Camera driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 24.1.1
    compositor: Hyprland v: 0.41.2-48-gf642fb97 driver: X: loaded: intel,nvidia
    unloaded: modesetting,nouveau dri: i965 gpu: i915 resolution:
    1: 3840x2160~60Hz 2: 2560x1440~60Hz
  API: EGL v: 1.5 drivers: iris,nvidia,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: intel mesa v: 24.1.5-arch1.2
    renderer: Mesa Intel UHD Graphics (CML GT2)
  API: Vulkan v: 1.3.285 drivers: nvidia,intel surfaces: xcb,xlib,wayland
  ```
[hyprland.log](https://github.com/user-attachments/files/16501932/hyprland.log)


[hyprland.conf.txt](https://github.com/user-attachments/files/16502110/hyprland.conf.txt)

I have seen `[LOG] [AQ] libseat: Device /dev/dri/card1 does not support kms` 
no clue if I need `linux-headers` package, but on the stable release everything is fine. 

PS: for testing I used only 
`monitor=,preferred, auto, auto` which also doesn't work.

No pressure guys, I just wanted to have it documented
